### ISSUE TITLE
Question about WEIZZ experiment

### ISSUE THREAD

**Issue by jchoi2022** [andreafioraldi/weizz-fuzzer#3]
Hello, I am a developer of Eclipser and want to ask some question about the experiments in the WEIZZ paper.

First, congratulations for the paper and thank you for releasing the tool on GitHub!

I looked into your paper and found that Eclipser was used in the experiment for the comparison with other fuzzers. While we believe it's reasonable that WEIZZ achieves higher coverage than Eclipser, we found it strange that AFL greatly outperforms Eclipser in some programs like mpg321 and readelf.

So we tried to find out what kind of issue was blocking Eclipser from increasing coverage. However, we are having trouble in reproducing the results reported in the paper.

We used the Dockerfile in [docker-env.zip](https://github.com/andreafioraldi/weizz-fuzzer/files/5004793/docker-env.zip) to setup 64bit Debian-9.2 with AFL-2.53b and Eclipser. First we are focusing on mpg321 and readelf for now, and built their specified versions. We fuzzed each program with `mpg321 input` and `readelf -a input` options. We did not provide AFL with dictionaries here, since the default AFL is not equipped with dictionaries for these formats. For more details, please refer to the bash scripts in the attached zip file.
                                                                                 
In our dockerized environment, we observed the following results:
- Eclipser continuously increases coverage throughout several hours in mpg321, and even finds out SIGSEGV crash from it. This is different from the results in Figure 6 and Table 7.
- Meanwhile, AFL fails to launch fork server on mpg321, and therefore fails to generate any test case. Should we make a take-around by disabling fork server?
- In readelf, we observed that Eclipser achieves much higher (more than twice) coverage than AFL after 12 hours of fuzzing. This is also different from Figure 6.

Possible causes we could think of were:
- Maybe we provided different command-line options for mpg321 and readelf?
- Maybe there's a difference in the method to measure basic block coverage?  We used QEMU to measure basic block coverage, and actually observed much higher number of basic blocks than Figure 6 (in overall). Could you share your tool for coverage measurement?
- Maybe Eclipser was misconfigured in some way?

Could you take a look at the Dockerfile and scripts we used, and let us know if there's anything wrong we did? Or if you can share the scripts you used for the experiments, we will take a look and try to figure out by ourselves.
                                                                
Thank you.

**Comment by andreafioraldi** [comment]
Hi, yes I also was surprised when i did the experiments. Not at the pc now, but iirc I used the command line in the eclipser readme. AFL uses also a dictionary, and this helps a lot.

**Comment by andreafioraldi** [comment]
Btw I also used translation blocks of qemu. Looked super strange to me but then also in fuzzbench AFL outperforms Eclipser so I didn't investigate anymore

**Comment by andreafioraldi** [comment]
For the command line of the tools, I used the ones from the aflsmart paper (so more complex than readelf -a)

**Comment by andreafioraldi** [comment]
From the paper `We also provide AFL with format-specific dictionaries to aid it with magic numbers`, AFL++ instead, having CompCov to bypass magics, does not have it. This makes sense, especially looking at tcpdump. If we look at fuzzbench's libpcap https://www.fuzzbench.com/reports/2020-06-30-and-05-24/index.html#libpcap_fuzz_both-summary Eclipser performs better than AFL but not at the level of AFL++ QEMU that can bypass magic bytes.

**Comment by andreafioraldi** [comment]
However, mpg321 continue to look strange, the command line is `mpg321 --stdout @@`, Eclipser was run with `dotnet ~/Eclipser/build/Eclipser.dll fuzz -p BINPATH -v 1 -i zero_in -t 86400 -o out/BINARY/FUZZER_TIME/ --src file --initarg \"ARGS\" -f /tmp/BINARY_TIME.input`
If this is not the preferred configuration, I would be happy to update the preprint saying that this is just one particular mode of Eclipser, It will not change the results in the paper for sure.

**Comment by andreafioraldi** [comment]
One thing that you can try is to disable trimming. when starting from an invalid seed, all '0' in this case, trimming could be the cause of a reduction of the input size so that bypassing the first roadblocks in impossible. take for instance PNG, if trimming reduces the size of the testcase to 1 you cannot match the first magic that are 8 bytes (137 80 78 71 13 10 26 10)

**Comment by andreafioraldi** [comment]
So, in the end, I would explain the results on readelf simply thanks to the dictionary, for mpg321 I'm investigating and I'll update you here ASAP.

**Comment by jchoi2022** [comment]
Thank you for the response.                                                      
                                                                                 
First I will retry with the options you mentioned, and let you know what we can observe.
                                                                                 
In the meantime, here are some more questions I'd like to ask.                   
                                                                                 
- Which command-line option did you provide to objdump? It's not included in AFLSmart paper.
- It's strange that the number of basic block differs greatly if you also used QEMU for the measurement. Maybe that this is because we measured basic block from shared library (.so) as well. I assume that you only counted the basic blocks from main program, am I right?
- It seems you manually constructed dictionaries for formats like MPG, ELF, etc, which are not provided in the default AFL. I think this partially explains why AFL performed better than our expectation. Could you share the dictionaries for MPG and ELF formats so we can reproduce the results?
- We cannot find a built-in option or environment variable that can only disable trimming  feature of AFL. Did you manually commented out the source code lines for trimming feature?
                                                                                 
Regarding Fuzzbench you mentioned, its benchmark programs mostly use well-formed seed corpus or have short-sized magic bytes in the format. In such case, it's not surprising that Eclipser cannot outperform other fuzzers, since the one of main contribution of Eclipser was in finding such magic byte automatically from scratch.
                                                                                 
However for readelf and mpg321, we knew that Eclipser performs quite well when dummy seeds are given, so that's why we found the result strange.
                                                                                 
Anyway, I will take more look and make update.

**Comment by andreafioraldi** [comment]
1. `objdump  -g -x @@`. 

2. No, all binutils targets are compiled with static libraries, so it is different from using distro's binaries. Libbfd is in the main binary, if you use distro binary you should use AFL_INST_LIBS=1. Fuzzing libraries is interesting, not programs around them.

3. https://github.com/aflsmart/aflsmart/tree/master/dictionaries, for mpg just `header_magic_mpg="\xff\xe3\x18\xc4"`

4. This was a suggestion for eclipser, I used trimming in the eval. For AFL++, if you want to try, it is AFL_DISABLE_TRIM.

**Comment by jchoi2022** [comment]
2. I also built the binutils binaries from source code, so Libbfd code must be embedded in the main binary in my setting, too. Still, code in libc.so can make a difference in the number of visited basic blocks. And for mpg321, it seems like the most of the parsing code exist in the shared library, and the number of measured basic block differ greatly. We observe much higher number of basic blocks than several hundreds.
                                                                                 
4. So you mean that you did not disable AFL's seed trimming in your experiment. Then I will use the same setting, since my goal is in reproducing the experiment result.

**Comment by jchoi2022** [comment]
Based on some experiments, I found that Eclipser was ran with a maximum file length limited to 72-byte, which significantly constrained it from increasing code coverage.
                                                                                 
Since Eclipser was originally intended as a replacement of concolic testing tool, its configuration parameter was aligned with that of KLEE, where maximum file length was limited to 8 byte. Since your Eclipser command is not providing option for maximum file length, the default 8-byte limitation is used for the fuzzing. Now when Eclipser is provided with the initial seed of 72-byte, this seed's length already exceeds the given limitation and therefore Eclipser does not extend the size of input anymore. In effect, Eclipser runs with a maximum file length limited to 72 byte.
                                                                                 
I think that you are already aware of the default parameter of Eclipser (as you mentioned this in one of the Fuzzbench repo issue), and this configuration actually makes a substantial difference in the result.
                                                                                 
I ran Eclipser `--maxfilelen 1048576` with option, to run in the same condition with AFL, and observed that it achieves significantly higher coverage than the default parameter. With this parameter, Eclipser covered 0.9K more basic blocks for `readelf`, 2.0K more for `objdump`, and 2.8K more for `mpg321` in average. The exact number may differ, since I measured basic blocks in different ways and repeated the run only for two times. If you want us to use your tool for the basic block measurement, feel free to share your tool.
                                                                                 
Also, I compared this result with the AFL's result (ran with the signatures you specified). For `readelf` and `objdump`, Eclipser outperformed AFL in terms of coverage, and for `mpg321` I could not compare against AFL's coverage, due to the issue I reported above. However, since Eclipser found a SIGSEGV crash from `mpg321` whereas AFL could not (according to your paper), I believe it's okay to say Eclipser explored more code than AFL for `mpg321`, too.
                                                                                 
For the other three programs where AFL outperformed Eclipser (i.e. `djpeg`, `libpng`, `gif2rgb`), we did not have time to run the experiment. However, we believe it may possible that AFL outperforms Eclipser if a good set of file format signature is given. Still, at least for `readelf`, `objdump`, and `mpg321`, the misconfigured maximum file length limitation has served as a big disadvantage for Eclipser.

**Comment by vanhauser-thc** [comment]
@jchoi2022 
according to a current fuzzbench run (https://www.fuzzbench.com/reports/2020-08-03/index.html) eclipser is outperformed by vanilla afl qemu mode (and afl++ qemu by a long run). when you claim eclipser i able to outperform afl and weizz - is the fuzzbench eclipser instance setup badly?

**Comment by jchoi2022** [comment]
No, Fuzzbench was configured with correct parameter.

To rephrase the comment I put above, Fuzzbench's programs mostly use well-formed seed corpus or have short-sized magic bytes in the input format. In such case, it's not surprising that AFL-QEMU outperforms Eclipser, since one of main focus of Eclipser was in automatically finding long magic bytes that are hard to be found with random fuzzing. We not that Eclipser's random fuzzing module is not as optimized as AFL (e.g. lack of persistent mode, lack of deterministic phase, etc.), so if Eclipser's magic byte identification does not have many chance to play its role, Eclipser is likely to perform worse than AFL.

However for programs like objdump and readelf, I knew that these programs have many long magic bytes, so found it strange that Eclipser performed worse than AFL even though dummy (not well-formed) seed was given.

I admit that Eclipser is not a tool that can _always_ outperform AFL. I just wanted to point out that there are certain situations where Eclipser's grey-box concolic testing technique can complementing the drawback of random fuzzing. Programs like objdump, readelf, mpg321, oggdec, and tcpdump used in the experiment are such examples.

P.S. Regarding WEIZZ, actually I think it's reasonable that WEIZZ achieves higher coverage than Eclipser, as I stated in the first comment. It considers and handles more various cases than Eclipser. I just compared Eclipser against AFL in my experiment.

**Comment by andreafioraldi** [comment]
>  I think that you are already aware of the default parameter of Eclipser

Yes ofc I found the parameter in your code for fuzzbench after the weizz submission, and could be that this parameter affects eclipser on some targets. Back in the time I ran a couple of experiments again after submission to see if the parameter could affect so much eclipser in this eval and I didn't noticed much difference, but I'll try again when I will have time on readelf for sure and update you.

It is fair to specify that this is a particular configuration of Eclipser that can affect the result of the fuzzer (not a misconf I would say, I just followed your readme) so of course, I will update the online preprint to clarify this :)

I suggest you btw to insert more info about this parameter in the readme for the future evals cause I found it just by chance.

**Comment by andreafioraldi** [comment]
What about calling this Basic or Klee mode of Eclipser?

**Comment by jchoi2022** [comment]
Yes, I agree that Ecliser's README should be updated. We initially thought users will pay enough attention to `--maxfilelen` option, since maximum file length is a critical parameter for concolic testing tool like KLEE. However, as more and more people are considering Eclipser as a fuzzer (and for fuzzer, this parameter is not so critical and AFL uses a hard-coded value for this parameter), it's understandable that users just use the default parameter for maximum file length. We should have stated in the README that we used `--maxfilelen 1048576` option for the comparison against AFL in the paper.


I would prefer 'KLEE mode' or 'KLEE configuration', since we did not intend this default parameter to be used as a standard or universal parameter. Also, we may align the default parameter with AFL in the future, and in that case 'Basic mode' may sound awkward. I think it would be good to insert an explanation after the sentence `Eclipser with its latest release when we ran our tests (commit 8a00591) and its default configuration.` that this 'default configuration' is aligned with KLEE's configuration, where the maximum file length is limited to a small value. But of course the decision is up to you.

**Comment by andreafioraldi** [comment]
> Eclipser with its latest release when
we ran our tests (commit 8a00591) and its default configuration,
aligned with KLEE. Note that this is only one of the possible con-
figurations of Eclipser, in particular this one is limited to a small
file length.

I'll close the issue, feel free to reach me directly by mail for other questions.
