### ISSUE TITLE
Maybe something wrong in get_deps.c function place_tags()

### ISSUE THREAD

**Issue by imbawenzi** [andreafioraldi/weizz-fuzzer#5]
from line 550 to line 591
it looks like the variable f_v0_i is always -1
so line 576 will never execute, v0_near_bytes_num is 0 forever, but I think it can't be 0 forever
is there any bugs in this function?
or maybe I misunderstood
Please give me a help，thanks!

**Comment by imbawenzi** [comment]
in tag.c get_random_chunk() function, parameter build_kind is UR(3) which is random 0,1,2.
but the code is
switch (build_kind) {
    case 0:
    case 1: {do something}
    case 2: {do something}
    case 3: {do something}
}
i think it might also have something wrong.

**Comment by andreafioraldi** [comment]
Yes the code was quickly changed for github, there is a typo here https://github.com/andreafioraldi/weizz-fuzzer/blob/master/src/get_deps.c#L556
ty.
